services:
  - type: web
    name: trap-str-ufo
    env: node
    region: ohio
    plan: free
    buildCommand: |
      npm install
      npm run build
      mkdir -p /data/images
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        value: 8027055639:AAElTX4rQUFkBEJYz80AAn5K7iFddExw4Nk
      - key: ADMIN_USERNAME
        value: Barter31Babee
      - key: ADMIN_CHAT_ID
        value: "5666579908"
      - key: PORT
        value: "3000"
      - key: IMAGES_PATH
        value: /data/images
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true
